// AUTO-GENERATED by scripts/build-lookup.js — do not edit by hand.
// Re-run: node scripts/build-lookup.js
const WLASL_URLS = {
  "apple": [
    "http://aslbricks.org/New/ASL-Videos/apple.mp4",
    "https://www.handspeak.com/word/a/apple.mp4",
    "https://www.signingsavvy.com/signs/mp4/7/7981.mp4",
    "http://www.aslsearch.com/signs/videos/apple.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/AP/APPLE-2072.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/AP/APPLE-2073.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/AP/APPLE-406.mp4",
    "https://media.spreadthesign.com/video/mp4/13/455436.mp4",
    "https://media.spreadthesign.com/video/mp4/13/480702.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/apple-2.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/apple.mp4",
    "https://media.asldeafined.com/vocabulary/1466511662.3373.mp4"
  ],
  "chair": [
    "https://media.spreadthesign.com/video/mp4/13/74909.mp4",
    "http://www.aslsearch.com/signs/videos/chair.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/chair.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Chair-mVdtJjs-_20.mp4",
    "https://media.asldeafined.com/vocabulary/1466729509.9229.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/CH/CHAIR-378.mp4",
    "https://www.handspeak.com/word/c/chair.mp4",
    "https://www.signingsavvy.com/signs/mp4/7/7821.mp4"
  ],
  "table": [
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Booth%2C%20Desk%2C%20Table-8QbAD7Y9UEk.mp4",
    "http://www.aslsearch.com/signs/videos/counter2.mp4",
    "https://media.asldeafined.com/vocabulary/1468942806.9415.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/table.mp4",
    "https://www.handspeak.com/word/t/table.mp4",
    "https://www.signingsavvy.com/signs/mp4/9/9252.mp4"
  ],
  "glass": [
    "http://aslbricks.org/New/ASL-Videos/glass.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/GL/GLASS-144.mp4",
    "https://www.signingsavvy.com/signs/mp4/8/8574.mp4",
    "https://media.spreadthesign.com/video/mp4/13/456451.mp4",
    "http://www.aslsearch.com/signs/videos/glass.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/glass.mp4",
    "https://media.asldeafined.com/vocabulary/1468549066.4394.mp4"
  ],
  "knife": [
    "https://media.spreadthesign.com/video/mp4/13/457473.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Knife-CAfDahqUXr4.mp4",
    "https://www.handspeak.com/word/k/knife.mp4",
    "https://www.signingsavvy.com/signs/mp4/23/23039.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/KN/KNIFE-167.mp4",
    "http://www.aslsearch.com/signs/videos/knife.mp4",
    "https://media.spreadthesign.com/video/mp4/13/457472.mp4"
  ],
  "kitchen": [
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Pancake%2C%20Kitchen-JYixqJW5ISo.mp4",
    "https://media.asldeafined.com/vocabulary/1468670630.8329.mp4",
    "https://www.handspeak.com/word/k/kitchen.mp4",
    "https://www.signingsavvy.com/signs/mp4/14/14239.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/KI/KITCHEN-557.mp4",
    "http://www.aslsearch.com/signs/videos/kitchen.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/kitchen.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Kitchen-WgJSoEOaHMo.mp4"
  ],
  "hungry": [
    "http://www.aslsearch.com/signs/videos/hunger.mp4",
    "https://media.spreadthesign.com/video/mp4/13/58529.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/hungry.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Hungry-FkoOUSVF-9g.mp4",
    "https://media.asldeafined.com/vocabulary/1468639252.5637.mp4",
    "https://www.handspeak.com/word/h/hungry.mp4",
    "https://www.signingsavvy.com/signs/mp4/7/7294.mp4"
  ],
  "water": [
    "https://www.handspeak.com/word/w/water.mp4",
    "https://www.signingsavvy.com/signs/mp4/22/22969.mp4",
    "https://www.signingsavvy.com/signs/mp4/22/22970.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/WA/WATER-1414.mp4",
    "http://www.aslsearch.com/signs/videos/water.mp4",
    "https://media.spreadthesign.com/video/mp4/13/486561.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/water.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Water-4xQijOap0PY.mp4",
    "https://media.asldeafined.com/vocabulary/1468927236.4055.mp4"
  ],
  "morning": [
    "http://www.aslsearch.com/signs/videos/morning.mp4",
    "https://media.spreadthesign.com/video/mp4/13/48602.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/morning.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Morning-Oem8EmGkQ0M.mp4",
    "https://media.asldeafined.com/vocabulary/1468716608.8519.mp4",
    "https://www.handspeak.com/word/m/morning.mp4",
    "https://www.signingsavvy.com/signs/mp4/14/14715.mp4"
  ],
  "eat": [
    "http://aslbricks.org/New/ASL-Videos/eat.mp4",
    "https://www.handspeak.com/word/e/eat-iclpop.mp4",
    "https://www.handspeak.com/word/e/eat.mp4",
    "https://www.signingsavvy.com/signs/mp4/14/14883.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/EA/EAT-399.mp4",
    "https://media.spreadthesign.com/video/mp4/13/74980.mp4",
    "http://www.aslsearch.com/signs/videos/eat.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/eat.mp4",
    "https://media.asldeafined.com/vocabulary/1468347821.5825.mp4"
  ],
  "drink": [
    "http://aslbricks.org/New/ASL-Videos/drink.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/DR/DRINK-119.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/drink.mp4",
    "http://www.aslsearch.com/signs/videos/drink-alcohol.mp4",
    "https://aslsignbank.haskins.yale.edu/dictionary/protected_media/glossvideo/ASL/DR/DRINK-120.mp4",
    "http://www.aslsearch.com/signs/videos/drink.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Drink%20(correct)-0UzEF7ru0sQ.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Drink-L6hHRIQzWBo.mp4",
    "https://media.asldeafined.com/vocabulary/1467773819.9825.mp4",
    "https://www.handspeak.com/word/d/drink2.mp4",
    "https://www.handspeak.com/word/d/drink-alcohol.mp4",
    "https://www.handspeak.com/word/d/drink-british.mp4",
    "https://www.handspeak.com/word/d/drink.mp4",
    "https://www.handspeak.com/word/d/drink-mug.mp4",
    "https://media.spreadthesign.com/video/mp4/13/153289.mp4",
    "https://www.handspeak.com/word/d/drink-plu.mp4",
    "https://www.signingsavvy.com/signs/mp4/14/14885.mp4",
    "https://www.signingsavvy.com/signs/mp4/23/23388.mp4",
    "https://www.signingsavvy.com/signs/mp4/23/23388.mp4",
    "https://www.signingsavvy.com/signs/mp4/23/23389.mp4",
    "https://www.signingsavvy.com/signs/mp4/7/7796.mp4"
  ],
  "food": [
    "http://aslbricks.org/New/ASL-Videos/food.mp4",
    "https://media.spreadthesign.com/video/mp4/13/74992.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/food.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/SignSchool%20Food.mp4",
    "https://media.asldeafined.com/vocabulary/1468513144.2894.mp4",
    "https://www.handspeak.com/word/f/food.mp4",
    "https://www.signingsavvy.com/signs/mp4/14/14883.mp4",
    "http://www.aslsearch.com/signs/videos/eat.mp4"
  ],
  "cup": [
    "https://media.spreadthesign.com/video/mp4/13/74958.mp4",
    "http://www.aslsearch.com/signs/videos/cup.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/db_uploads/SignSchool%20Cup-nG2mw4Jjp94.mp4",
    "https://media.asldeafined.com/vocabulary/1466905724.9794.mp4",
    "https://www.handspeak.com/word/c/cup.mp4",
    "https://www.signingsavvy.com/signs/mp4/23/23013.mp4",
    "https://www.signingsavvy.com/signs/mp4/23/23014.mp4"
  ],
  "bread": [
    "http://www.aslsearch.com/signs/videos/bread.mp4",
    "https://media.spreadthesign.com/video/mp4/13/74891.mp4",
    "https://s3-us-west-1.amazonaws.com/files.startasl.com/asldictionary/bread.mp4",
    "https://signstock.blob.core.windows.net/signschool/videos/SignSchool%20Bread.mp4",
    "https://media.asldeafined.com/vocabulary/1466723620.5444.mp4",
    "https://www.handspeak.com/word/b/bread.mp4",
    "https://www.signingsavvy.com/signs/mp4/7/7902.mp4",
    "https://www.signingsavvy.com/signs/mp4/8/8391.mp4"
  ]
};
