/**
 * build-lookup.js
 *
 * Reads WLASL_v0.3.json and generates ../wlasl-urls.js — a lightweight
 * browser-ready lookup of direct mp4 URLs for every word in VOCAB_WORDS.
 *
 * Run whenever you add a new word to the scene:
 *   node scripts/build-lookup.js
 */

const fs   = require('fs');
const path = require('path');

// ── Add new words here as you expand the scene ──────────────────────────────
const VOCAB_WORDS = [
  // Kitchen story — scene objects
  'apple', 'chair', 'table', 'glass', 'knife',
  // Kitchen story — story words
  'kitchen', 'hungry', 'water', 'morning', 'eat', 'drink', 'food', 'cup', 'bread',
  // Doctor story — coverable words (43 from lint-story.js)
  'doctor', 'sit', 'tall', 'quiet', 'hospital', 'room', 'feel', 'very', 'sick',
  'tired', 'today', 'keep', 'eyes', 'door', 'because', 'cannot', 'hear', 'name',
  'soon', 'nurse', 'call', 'enter', 'deaf', 'down', 'see', 'temperature',
  'explain', 'bad', 'winter', 'cold', 'go', 'home', 'warm', 'rest',
  'comfortable', 'bed', 'type', 'phone', 'visit', 'safe',
  // Airport story — coverable words (Session 7)
  'ticket', 'people', 'walk', 'write',
  // Restaurant story — coverable words (Session 7)
  'restaurant', 'family', 'chicken', 'order',
  // Classroom story — coverable words (Session 7)
  'class', 'teacher', 'group', 'project', 'computer', 'paper', 'question',
  'help', 'read',
  // Phone story — coverable words (Session 7)
  'problem', 'bank', 'number', 'time', 'person',
];

const ROOT      = path.join(__dirname, '..');
const JSON_PATH = path.join(ROOT, 'WLASL_v0.3.json');
const OUT_PATH  = path.join(ROOT, 'wlasl-urls.js');

console.log('Reading WLASL_v0.3.json …');
const data = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));

const lookup = {};
const missing = [];

VOCAB_WORDS.forEach(word => {
  const entry = data.find(e => e.gloss.toLowerCase() === word.toLowerCase());
  if (!entry) {
    missing.push(word);
    return;
  }
  // Prefer direct .mp4 links; skip YouTube and other non-mp4 sources
  const urls = entry.instances
    .filter(i => i.url && i.url.toLowerCase().endsWith('.mp4'))
    .map(i => i.url);

  if (urls.length === 0) {
    missing.push(word);
    console.warn(`  ⚠  No direct mp4 found for "${word}"`);
  } else {
    lookup[word] = urls;
    console.log(`  ✓  ${word}: ${urls.length} URL(s)`);
  }
});

if (missing.length) {
  console.warn('\nMissing words (no direct mp4):', missing.join(', '));
}

const output = `// AUTO-GENERATED by scripts/build-lookup.js — do not edit by hand.
// Re-run: node scripts/build-lookup.js
const WLASL_URLS = ${JSON.stringify(lookup, null, 2)};
`;

fs.writeFileSync(OUT_PATH, output, 'utf8');
console.log(`\nWrote ${OUT_PATH} (${(output.length / 1024).toFixed(1)} KB)`);
